const movies = [
  {
    id: 1,
    title: "쇼생크 탈출",
    englishTitle: "The Shawshank Redemption",
    year: 1994,
    genre: ["드라마"],
    aliases: ["쇼생크 탈출", "The Shawshank Redemption", "Shawshank"],
    director: "프랭크 다라본트",
    actors: ["팀 로빈스", "모건 프리먼"],
    poster: "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
    ratings: { imdb: 9.3, cine21: "없음", rottenTomatoes: 89, letterboxd: 4.6 },
    description: "억울한 누명을 쓰고 교도소에 수감된 앤디가 희망을 지켜가는 이야기."
  },
  {
    id: 2,
    title: "대부",
    englishTitle: "The Godfather",
    year: 1972,
    genre: ["범죄", "드라마"],
    aliases: ["대부", "The Godfather", "Godfather"],
    director: "프랜시스 포드 코폴라",
    actors: ["말론 브란도", "알 파치노"],
    poster: "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
    ratings: { imdb: 9.2, cine21: 8.67, rottenTomatoes: 97, letterboxd: 4.51 },
    description: "코를레오네 가문의 권력과 가족을 둘러싼 범죄 드라마."
  },
  {
    id: 3,
    title: "대부 2",
    englishTitle: "The Godfather Part II",
    year: 1974,
    genre: ["범죄", "드라마"],
    aliases: ["대부 2", "대부2", "The Godfather Part II"],
    director: "프랜시스 포드 코폴라",
    actors: ["알 파치노", "로버트 드 니로"],
    poster: "https://upload.wikimedia.org/wikipedia/en/0/03/Godfather_part_ii.jpg",
    ratings: { imdb: 9.0, cine21: 9.00, rottenTomatoes: 96, letterboxd: 4.58 },
    description: "마이클 코를레오네와 비토 코를레오네의 이야기를 교차해 보여주는 작품."
  },
  {
    id: 4,
    title: "다크 나이트",
    englishTitle: "The Dark Knight",
    year: 2008,
    genre: ["액션", "범죄", "드라마"],
    aliases: ["다크 나이트", "The Dark Knight", "Dark Knight"],
    director: "크리스토퍼 놀란",
    actors: ["크리스찬 베일", "히스 레저"],
    poster: "https://upload.wikimedia.org/wikipedia/en/8/8a/Dark_Knight.jpg",
    ratings: { imdb: 9.1, cine21: 8.56, rottenTomatoes: 94, letterboxd: 4.5 },
    description: "배트맨과 조커의 대결을 중심으로 한 범죄 액션 영화."
  },
  {
    id: 5,
    title: "기생충",
    englishTitle: "Parasite",
    year: 2019,
    genre: ["드라마", "스릴러"],
    aliases: ["기생충", "Parasite", "Gisaengchung"],
    director: "봉준호",
    actors: ["송강호", "이선균", "조여정", "최우식"],
    poster: "https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png",
    ratings: { imdb: 8.5, cine21: 9.09, rottenTomatoes: 99, letterboxd: 4.5 },
    description: "서로 다른 계층의 두 가족을 통해 사회의 격차를 그린 작품."
  },
  {
    id: 6,
    title: "인터스텔라",
    englishTitle: "Interstellar",
    year: 2014,
    genre: ["SF", "드라마", "어드벤처"],
    aliases: ["인터스텔라", "Interstellar"],
    director: "크리스토퍼 놀란",
    actors: ["매튜 맥커너히", "앤 해서웨이"],
    poster: "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
    ratings: { imdb: 8.7, cine21: 7.67, rottenTomatoes: 73, letterboxd: 4.4 },
    description: "인류의 생존을 위해 새로운 행성을 찾아 떠나는 우주 탐사 이야기."
  },
  {
    id: 7,
    title: "인셉션",
    englishTitle: "Inception",
    year: 2010,
    genre: ["SF", "액션", "미스터리", "스릴러"],
    aliases: ["인셉션", "Inception"],
    director: "크리스토퍼 놀란",
    actors: ["레오나르도 디카프리오", "조셉 고든 레빗"],
    poster: "https://upload.wikimedia.org/wikipedia/en/7/7f/Inception_ver3.jpg",
    ratings: { imdb: 8.8, cine21: 7.75, rottenTomatoes: 86, letterboxd: 4.4 },
    description: "꿈속에 들어가 생각을 심는 작전을 그린 SF 스릴러."
  },
  {
    id: 8,
    title: "반지의 제왕: 왕의 귀환",
    englishTitle: "The Lord of the Rings: The Return of the King",
    year: 2003,
    genre: ["판타지", "어드벤처", "드라마"],
    aliases: ["왕의 귀환", "The Return of the King", "LOTR"],
    director: "피터 잭슨",
    actors: ["일라이저 우드", "이안 맥켈런", "비고 모텐슨"],
    poster: "https://upload.wikimedia.org/wikipedia/en/4/43/The_Lord_of_the_Rings_Return_of_the_King.jpg",
    ratings: { imdb: 9.0, cine21: 8.33, rottenTomatoes: 94, letterboxd: 4.6 },
    description: "절대반지를 파괴하기 위한 마지막 여정을 그린 판타지 영화."
  },
  {
    id: 9,
    title: "올드보이",
    englishTitle: "Oldboy",
    year: 2003,
    genre: ["스릴러", "미스터리", "드라마"],
    aliases: ["올드보이", "Oldboy"],
    director: "박찬욱",
    actors: ["최민식", "유지태", "강혜정"],
    poster: "",
    ratings: { imdb: 8.3, cine21: 7.67, rottenTomatoes: 82, letterboxd: 4.2 },
    description: "오랜 시간 감금된 남자가 자신을 가둔 이유를 추적하는 이야기."
  },
  {
    id: 10,
    title: "살인의 추억",
    englishTitle: "Memories of Murder",
    year: 2003,
    genre: ["범죄", "드라마", "미스터리"],
    aliases: ["살인의 추억", "Memories of Murder"],
    director: "봉준호",
    actors: ["송강호", "김상경"],
    poster: "",
    ratings: { imdb: 8.1, cine21: 7.00, rottenTomatoes: 95, letterboxd: 4.2 },
    description: "한 지역에서 발생한 연쇄 사건을 추적하는 형사들의 이야기."
  },
  {
    id: 11,
    title: "마더",
    englishTitle: "Mother",
    year: 2009,
    genre: ["드라마", "미스터리", "스릴러"],
    aliases: ["마더", "Mother"],
    director: "봉준호",
    actors: ["김혜자", "원빈", "진구"],
    poster: "",
    ratings: { imdb: 7.7, cine21: 8.00, rottenTomatoes: 96, letterboxd: 4.0 },
    description: "아들의 사건에 직접 뛰어든 어머니의 이야기를 그린 미스터리 드라마."
  },
  {
    id: 12,
    title: "헤어질 결심",
    englishTitle: "Decision to Leave",
    year: 2022,
    genre: ["미스터리", "드라마", "로맨스"],
    aliases: ["헤어질 결심", "Decision to Leave"],
    director: "박찬욱",
    actors: ["박해일", "탕웨이"],
    poster: "",
    ratings: { imdb: 7.3, cine21: 8.73, rottenTomatoes: 94, letterboxd: 4.0 },
    description: "사건을 수사하는 형사와 용의자 사이의 미묘한 감정을 그린 작품."
  },
  {
    id: 13,
    title: "곡성",
    englishTitle: "The Wailing",
    year: 2016,
    genre: ["미스터리", "스릴러", "공포"],
    aliases: ["곡성", "The Wailing"],
    director: "나홍진",
    actors: ["곽도원", "황정민", "천우희"],
    poster: "",
    ratings: { imdb: 7.4, cine21: 8.14, rottenTomatoes: 99, letterboxd: 4.0 },
    description: "한 마을에서 벌어지는 기이한 사건들을 다룬 미스터리 영화."
  },
  {
    id: 14,
    title: "아가씨",
    englishTitle: "The Handmaiden",
    year: 2016,
    genre: ["드라마", "스릴러", "로맨스"],
    aliases: ["아가씨", "The Handmaiden"],
    director: "박찬욱",
    actors: ["김민희", "김태리", "하정우"],
    poster: "",
    ratings: { imdb: 8.1, cine21: 7.46, rottenTomatoes: 96, letterboxd: 4.1 },
    description: "1930년대 조선을 배경으로 펼쳐지는 심리 스릴러."
  },
  {
    id: 15,
    title: "부산행",
    englishTitle: "Train to Busan",
    year: 2016,
    genre: ["액션", "스릴러", "공포"],
    aliases: ["부산행", "Train to Busan"],
    director: "연상호",
    actors: ["공유", "정유미", "마동석"],
    poster: "",
    ratings: { imdb: 7.6, cine21: "없음", rottenTomatoes: 95, letterboxd: 3.9 },
    description: "부산으로 향하는 열차에서 벌어지는 생존 이야기."
  },
  {
    id: 16,
    title: "파묘",
    englishTitle: "Exhuma",
    year: 2024,
    genre: ["미스터리", "공포", "스릴러"],
    aliases: ["파묘", "Exhuma"],
    director: "장재현",
    actors: ["최민식", "김고은", "유해진", "이도현"],
    poster: "",
    ratings: { imdb: 6.9, cine21: 7.15, rottenTomatoes: 91, letterboxd: 3.5 },
    description: "수상한 묘를 이장하면서 벌어지는 미스터리 오컬트 영화."
  },
  {
    id: 17,
    title: "범죄도시",
    englishTitle: "The Outlaws",
    year: 2017,
    genre: ["액션", "범죄"],
    aliases: ["범죄도시", "The Outlaws"],
    director: "강윤성",
    actors: ["마동석", "윤계상"],
    poster: "",
    ratings: { imdb: 7.2, cine21: 6.00, rottenTomatoes: "없음", letterboxd: 3.3 },
    description: "강력반 형사들이 조직폭력 사건을 해결하는 액션 영화."
  },
  {
    id: 18,
    title: "범죄도시 2",
    englishTitle: "The Roundup",
    year: 2022,
    genre: ["액션", "범죄"],
    aliases: ["범죄도시2", "범죄도시 2", "The Roundup"],
    director: "이상용",
    actors: ["마동석", "손석구"],
    poster: "",
    ratings: { imdb: 7.0, cine21: 6.60, rottenTomatoes: "없음", letterboxd: 3.5 },
    description: "강력반 형사들이 해외 범죄자를 추적하는 액션 영화."
  },
  {
    id: 19,
    title: "신세계",
    englishTitle: "New World",
    year: 2013,
    genre: ["범죄", "액션", "드라마"],
    aliases: ["신세계", "New World"],
    director: "박훈정",
    actors: ["이정재", "황정민", "박성웅"],
    poster: "",
    ratings: { imdb: 7.5, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.8 },
    description: "경찰과 조직 사이에서 갈등하는 잠입 경찰의 이야기."
  },
  {
    id: 20,
    title: "달콤한 인생",
    englishTitle: "A Bittersweet Life",
    year: 2005,
    genre: ["액션", "범죄", "드라마"],
    aliases: ["달콤한 인생", "A Bittersweet Life"],
    director: "김지운",
    actors: ["이병헌", "김영철"],
    poster: "",
    ratings: { imdb: 7.5, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.8 },
    description: "조직의 명령을 어긴 남자가 위기에 빠지는 범죄 액션 영화."
  },
  {
    id: 21,
    title: "친절한 금자씨",
    englishTitle: "Lady Vengeance",
    year: 2005,
    genre: ["드라마", "스릴러"],
    aliases: ["친절한 금자씨", "Lady Vengeance"],
    director: "박찬욱",
    actors: ["이영애", "최민식"],
    poster: "",
    ratings: { imdb: 7.5, cine21: "없음", rottenTomatoes: 76, letterboxd: 3.8 },
    description: "오랜 시간 복수를 준비한 한 여자의 이야기를 그린 작품."
  },
  {
    id: 22,
    title: "복수는 나의 것",
    englishTitle: "Sympathy for Mr. Vengeance",
    year: 2002,
    genre: ["범죄", "드라마", "스릴러"],
    aliases: ["복수는 나의 것", "Sympathy for Mr. Vengeance"],
    director: "박찬욱",
    actors: ["송강호", "신하균", "배두나"],
    poster: "",
    ratings: { imdb: 7.5, cine21: "없음", rottenTomatoes: 54, letterboxd: 3.8 },
    description: "서로 다른 인물들의 복수가 이어지는 범죄 드라마."
  },
  {
    id: 23,
    title: "공동경비구역 JSA",
    englishTitle: "Joint Security Area",
    year: 2000,
    genre: ["드라마", "미스터리", "전쟁"],
    aliases: ["공동경비구역 JSA", "JSA", "Joint Security Area"],
    director: "박찬욱",
    actors: ["이영애", "송강호", "이병헌"],
    poster: "",
    ratings: { imdb: 7.8, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.8 },
    description: "판문점 공동경비구역에서 발생한 사건의 진실을 추적하는 영화."
  },
  {
    id: 24,
    title: "괴물",
    englishTitle: "The Host",
    year: 2006,
    genre: ["SF", "드라마", "스릴러"],
    aliases: ["괴물", "The Host"],
    director: "봉준호",
    actors: ["송강호", "변희봉", "배두나"],
    poster: "",
    ratings: { imdb: 7.1, cine21: "없음", rottenTomatoes: 93, letterboxd: 3.8 },
    description: "한강에 나타난 괴물과 가족의 사투를 그린 작품."
  },
  {
    id: 25,
    title: "박쥐",
    englishTitle: "Thirst",
    year: 2009,
    genre: ["드라마", "공포"],
    aliases: ["박쥐", "Thirst"],
    director: "박찬욱",
    actors: ["송강호", "김옥빈"],
    poster: "",
    ratings: { imdb: 7.1, cine21: "없음", rottenTomatoes: 81, letterboxd: 3.8 },
    description: "한 사제가 특별한 사건을 겪은 뒤 변화하는 이야기를 다룬 작품."
  },
  {
    id: 26,
    title: "버닝",
    englishTitle: "Burning",
    year: 2018,
    genre: ["드라마", "미스터리"],
    aliases: ["버닝", "Burning"],
    director: "이창동",
    actors: ["유아인", "스티븐 연", "전종서"],
    poster: "",
    ratings: { imdb: 7.5, cine21: "없음", rottenTomatoes: 95, letterboxd: 3.9 },
    description: "한 남자가 오랜만에 만난 여성을 둘러싼 미스터리에 빠지는 이야기."
  },
  {
    id: 27,
    title: "밀양",
    englishTitle: "Secret Sunshine",
    year: 2007,
    genre: ["드라마"],
    aliases: ["밀양", "Secret Sunshine"],
    director: "이창동",
    actors: ["전도연", "송강호"],
    poster: "",
    ratings: { imdb: 7.5, cine21: "없음", rottenTomatoes: 90, letterboxd: 4.0 },
    description: "밀양으로 이사한 한 여성이 삶의 큰 변화를 겪는 이야기."
  },
  {
    id: 28,
    title: "시",
    englishTitle: "Poetry",
    year: 2010,
    genre: ["드라마"],
    aliases: ["시", "Poetry"],
    director: "이창동",
    actors: ["윤정희", "이창동"],
    poster: "",
    ratings: { imdb: 7.8, cine21: 8.67, rottenTomatoes: 100, letterboxd: 4.0 },
    description: "시를 배우기 시작한 한 여성이 삶과 아름다움을 바라보는 이야기."
  },
  {
    id: 29,
    title: "8월의 크리스마스",
    englishTitle: "Christmas in August",
    year: 1998,
    genre: ["드라마", "로맨스"],
    aliases: ["8월의 크리스마스", "Christmas in August"],
    director: "허진호",
    actors: ["한석규", "심은하"],
    poster: "",
    ratings: { imdb: 7.5, cine21: 7.75, rottenTomatoes: "없음", letterboxd: 3.8 },
    description: "사진관을 운영하는 남자와 주차단속원 여자의 만남을 그린 작품."
  },
  {
    id: 30,
    title: "말아톤",
    englishTitle: "Marathon",
    year: 2005,
    genre: ["드라마"],
    aliases: ["말아톤", "Marathon"],
    director: "정윤철",
    actors: ["조승우", "김미숙"],
    poster: "",
    ratings: { imdb: 7.5, cine21: 7.00, rottenTomatoes: "없음", letterboxd: 3.6 },
    description: "달리기를 통해 자신의 가능성을 찾아가는 한 청년의 이야기."
  },
  {
    id: 31,
    title: "택시운전사",
    englishTitle: "A Taxi Driver",
    year: 2017,
    genre: ["드라마", "역사"],
    aliases: ["택시운전사", "A Taxi Driver"],
    director: "장훈",
    actors: ["송강호", "토마스 크레취만"],
    poster: "",
    ratings: { imdb: 7.9, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.7 },
    description: "서울의 택시기사가 외국 기자와 함께 광주로 향하는 이야기."
  },
  {
    id: 32,
    title: "1987",
    englishTitle: "1987: When the Day Comes",
    year: 2017,
    genre: ["드라마", "역사"],
    aliases: ["1987", "When the Day Comes"],
    director: "장준환",
    actors: ["김윤석", "하정우", "김태리"],
    poster: "",
    ratings: { imdb: 7.8, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.7 },
    description: "1987년 민주화 운동을 둘러싼 여러 인물의 이야기를 그린 작품."
  },
  {
    id: 33,
    title: "변호인",
    englishTitle: "The Attorney",
    year: 2013,
    genre: ["드라마", "법정"],
    aliases: ["변호인", "The Attorney"],
    director: "양우석",
    actors: ["송강호", "김영애", "오달수"],
    poster: "",
    ratings: { imdb: 7.7, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.5 },
    description: "한 변호사가 한 사건을 맡으며 사회의 부조리와 마주하는 이야기."
  },
  {
    id: 34,
    title: "극한직업",
    englishTitle: "Extreme Job",
    year: 2019,
    genre: ["코미디", "액션", "범죄"],
    aliases: ["극한직업", "Extreme Job"],
    director: "이병헌",
    actors: ["류승룡", "이하늬", "진선규"],
    poster: "",
    ratings: { imdb: 7.0, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.4 },
    description: "잠복수사를 위해 치킨집을 운영하게 된 형사들의 코미디."
  },
  {
    id: 35,
    title: "베테랑",
    englishTitle: "Veteran",
    year: 2015,
    genre: ["액션", "범죄"],
    aliases: ["베테랑", "Veteran"],
    director: "류승완",
    actors: ["황정민", "유아인"],
    poster: "",
    ratings: { imdb: 7.0, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.4 },
    description: "강력반 형사가 재벌 3세의 범죄를 추적하는 액션 영화."
  },
  {
    id: 36,
    title: "암살",
    englishTitle: "Assassination",
    year: 2015,
    genre: ["액션", "드라마", "역사"],
    aliases: ["암살", "Assassination"],
    director: "최동훈",
    actors: ["전지현", "이정재", "하정우"],
    poster: "",
    ratings: { imdb: 7.1, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.4 },
    description: "일제강점기를 배경으로 독립운동가들의 작전을 그린 영화."
  },
  {
    id: 37,
    title: "명량",
    englishTitle: "The Admiral: Roaring Currents",
    year: 2014,
    genre: ["액션", "역사", "전쟁"],
    aliases: ["명량", "The Admiral Roaring Currents"],
    director: "김한민",
    actors: ["최민식", "류승룡"],
    poster: "",
    ratings: { imdb: 7.1, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.2 },
    description: "이순신 장군의 명량해전을 소재로 한 역사 액션 영화."
  },
  {
    id: 38,
    title: "서울의 봄",
    englishTitle: "12.12: The Day",
    year: 2023,
    genre: ["드라마", "역사"],
    aliases: ["서울의 봄", "12.12: The Day"],
    director: "김성수",
    actors: ["황정민", "정우성", "이성민"],
    poster: "",
    ratings: { imdb: 8.0, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.9 },
    description: "1979년 서울에서 벌어진 정치적 격변을 다룬 작품."
  },
  {
    id: 39,
    title: "콘크리트 유토피아",
    englishTitle: "Concrete Utopia",
    year: 2023,
    genre: ["드라마", "스릴러", "재난"],
    aliases: ["콘크리트 유토피아", "Concrete Utopia"],
    director: "엄태화",
    actors: ["이병헌", "박서준", "박보영"],
    poster: "",
    ratings: { imdb: 6.6, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.5 },
    description: "대지진 이후 유일하게 남은 아파트를 중심으로 벌어지는 이야기."
  },
  {
    id: 40,
    title: "도가니",
    englishTitle: "Silenced",
    year: 2011,
    genre: ["드라마"],
    aliases: ["도가니", "Silenced", "The Crucible"],
    director: "황동혁",
    actors: ["공유", "정유미"],
    poster: "",
    ratings: { imdb: 8.0, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.8 },
    description: "한 학교에서 벌어진 사건을 알게 된 교사의 이야기를 다룬 작품."
  },
  {
    id: 41,
    title: "추격자",
    englishTitle: "The Chaser",
    year: 2008,
    genre: ["범죄", "스릴러"],
    aliases: ["추격자", "The Chaser"],
    director: "나홍진",
    actors: ["김윤석", "하정우"],
    poster: "",
    ratings: { imdb: 7.8, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.9 },
    description: "실종된 사람들을 찾던 전직 형사가 사건의 진실을 추적하는 스릴러."
  },
  {
    id: 42,
    title: "황해",
    englishTitle: "The Yellow Sea",
    year: 2010,
    genre: ["범죄", "액션", "스릴러"],
    aliases: ["황해", "The Yellow Sea"],
    director: "나홍진",
    actors: ["하정우", "김윤석"],
    poster: "",
    ratings: { imdb: 7.3, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.7 },
    description: "한 남자가 빚을 갚기 위해 위험한 의뢰를 맡는 범죄 스릴러."
  },
  {
    id: 43,
    title: "타짜",
    englishTitle: "Tazza: The High Rollers",
    year: 2006,
    genre: ["범죄", "드라마"],
    aliases: ["타짜", "Tazza", "The High Rollers"],
    director: "최동훈",
    actors: ["조승우", "김혜수", "백윤식"],
    poster: "",
    ratings: { imdb: 7.2, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.6 },
    description: "도박판에 뛰어든 한 남자의 성장과 복수를 그린 범죄 영화."
  },
  {
    id: 44,
    title: "내부자들",
    englishTitle: "Inside Men",
    year: 2015,
    genre: ["범죄", "드라마", "스릴러"],
    aliases: ["내부자들", "Inside Men"],
    director: "우민호",
    actors: ["이병헌", "조승우", "백윤식"],
    poster: "",
    ratings: { imdb: 7.0, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.6 },
    description: "정치와 언론, 재벌의 관계를 다룬 범죄 드라마."
  },
  {
    id: 45,
    title: "아저씨",
    englishTitle: "The Man from Nowhere",
    year: 2010,
    genre: ["액션", "범죄", "스릴러"],
    aliases: ["아저씨", "The Man from Nowhere"],
    director: "이정범",
    actors: ["원빈", "김새론"],
    poster: "",
    ratings: { imdb: 7.7, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.7 },
    description: "한 남자가 이웃 소녀를 구하기 위해 사건에 뛰어드는 액션 영화."
  },
  {
    id: 46,
    title: "엽기적인 그녀",
    englishTitle: "My Sassy Girl",
    year: 2001,
    genre: ["로맨스", "코미디"],
    aliases: ["엽기적인 그녀", "My Sassy Girl"],
    director: "곽재용",
    actors: ["전지현", "차태현"],
    poster: "",
    ratings: { imdb: 8.0, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.6 },
    description: "대학생 견우와 독특한 성격의 여성이 만나면서 벌어지는 이야기."
  },
  {
    id: 47,
    title: "봄 여름 가을 겨울 그리고 봄",
    englishTitle: "Spring, Summer, Fall, Winter... and Spring",
    year: 2003,
    genre: ["드라마"],
    aliases: ["봄 여름 가을 겨울 그리고 봄", "Spring Summer Fall Winter and Spring"],
    director: "김기덕",
    actors: ["오영수", "김영민"],
    poster: "",
    ratings: { imdb: 7.8, cine21: "없음", rottenTomatoes: 95, letterboxd: 3.9 },
    description: "계절의 변화 속에서 인간의 삶과 성장을 바라보는 작품."
  },
  {
    id: 48,
    title: "빈집",
    englishTitle: "3-Iron",
    year: 2004,
    genre: ["드라마", "로맨스"],
    aliases: ["빈집", "3-Iron"],
    director: "김기덕",
    actors: ["재희", "이승연"],
    poster: "",
    ratings: { imdb: 7.9, cine21: "없음", rottenTomatoes: 95, letterboxd: 3.9 },
    description: "빈집을 돌아다니던 남자와 한 여자의 특별한 관계를 그린 작품."
  },
  {
    id: 49,
    title: "김씨 표류기",
    englishTitle: "Castaway on the Moon",
    year: 2009,
    genre: ["드라마", "코미디", "로맨스"],
    aliases: ["김씨 표류기", "Castaway on the Moon"],
    director: "이해준",
    actors: ["정재영", "정려원"],
    poster: "",
    ratings: { imdb: 7.9, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.8 },
    description: "도시 한가운데에서 홀로 살아가게 된 두 사람의 이야기."
  },
  {
    id: 50,
    title: "악마를 보았다",
    englishTitle: "I Saw the Devil",
    year: 2010,
    genre: ["범죄", "스릴러"],
    aliases: ["악마를 보았다", "I Saw the Devil"],
    director: "김지운",
    actors: ["이병헌", "최민식"],
    poster: "",
    ratings: { imdb: 7.8, cine21: "없음", rottenTomatoes: "없음", letterboxd: 3.7 },
    description: "한 남자가 범죄자를 추적하는 복수극."
  },
  {
    id: 51,
    title: "쇼생크 탈출",
    englishTitle: "The Shawshank Redemption",
    year: 1994,
    genre: ["드라마"],
    aliases: ["쇼생크 탈출", "The Shawshank Redemption"],
    director: "프랭크 다라본트",
    actors: ["팀 로빈스", "모건 프리먼"],
    poster: "",
    ratings: { imdb: 9.3, cine21: "없음", rottenTomatoes: 89, letterboxd: 4.6 },
    description: "교도소에서 희망을 잃지 않는 한 남자의 이야기."
  },
  {
    id: 52,
    title: "12명의 성난 사람들",
    englishTitle: "12 Angry Men",
    year: 1957,
    genre: ["드라마", "법정"],
    aliases: ["12명의 성난 사람들", "12 Angry Men"],
    director: "시드니 루멧",
    actors: ["헨리 폰다", "리 J. 콥"],
    poster: "",
    ratings: { imdb: 9.0, cine21: "없음", rottenTomatoes: 100, letterboxd: 4.5 },
    description: "배심원들이 한 사건의 유죄 여부를 두고 토론하는 법정 드라마."
  },
  {
    id: 53,
    title: "쉰들러 리스트",
    englishTitle: "Schindler's List",
    year: 1993,
    genre: ["드라마", "역사", "전쟁"],
    aliases: ["쉰들러 리스트", "Schindler's List"],
    director: "스티븐 스필버그",
    actors: ["리암 니슨", "벤 킹슬리", "랄프 파인즈"],
    poster: "",
    ratings: { imdb: 9.0, cine21: "없음", rottenTomatoes: 98, letterboxd: 4.4 },
    description: "전쟁 속에서 사람들을 구하려 한 기업가의 이야기."
  },
  {
    id: 54,
    title: "펄프 픽션",
    englishTitle: "Pulp Fiction",
    year: 1994,
    genre: ["범죄", "드라마"],
    aliases: ["펄프 픽션", "Pulp Fiction"],
    director: "쿠엔틴 타란티노",
    actors: ["존 트라볼타", "사무엘 L. 잭슨", "우마 서먼"],
    poster: "",
    ratings: { imdb: 8.8, cine21: "없음", rottenTomatoes: 92, letterboxd: 4.3 },
    description: "여러 인물의 이야기가 독특한 구조로 얽히는 범죄 영화."
  },
  {
    id: 55,
    title: "파이트 클럽",
    englishTitle: "Fight Club",
    year: 1999,
    genre: ["드라마", "스릴러"],
    aliases: ["파이트 클럽", "Fight Club"],
    director: "데이비드 핀처",
    actors: ["브래드 피트", "에드워드 노튼"],
    poster: "",
    ratings: { imdb: 8.8, cine21: "없음", rottenTomatoes: 79, letterboxd: 4.2 },
    description: "무료한 삶을 살던 남자가 새로운 인물을 만나면서 변화하는 이야기."
  },
  {
    id: 56,
    title: "매트릭스",
    englishTitle: "The Matrix",
    year: 1999,
    genre: ["SF", "액션"],
    aliases: ["매트릭스", "The Matrix"],
    director: "릴리 워쇼스키, 라나 워쇼스키",
    actors: ["키아누 리브스", "로렌스 피시번"],
    poster: "",
    ratings: { imdb: 8.7, cine21: "없음", rottenTomatoes: 83, letterboxd: 4.2 },
    description: "현실이라고 믿었던 세계의 진실을 알게 되는 SF 액션 영화."
  },
  {
    id: 57,
    title: "포레스트 검프",
    englishTitle: "Forrest Gump",
    year: 1994,
    genre: ["드라마", "로맨스"],
    aliases: ["포레스트 검프", "Forrest Gump"],
    director: "로버트 저메키스",
    actors: ["톰 행크스", "로빈 라이트"],
    poster: "",
    ratings: { imdb: 8.8, cine21: "없음", rottenTomatoes: 71, letterboxd: 4.1 },
    description: "한 남자의 삶을 통해 미국 현대사의 여러 순간을 보여주는 영화."
  },
  {
    id: 58,
    title: "세븐",
    englishTitle: "Se7en",
    year: 1995,
    genre: ["범죄", "미스터리", "스릴러"],
    aliases: ["세븐", "Se7en", "Seven"],
    director: "데이비드 핀처",
    actors: ["브래드 피트", "모건 프리먼"],
    poster: "",
    ratings: { imdb: 8.6, cine21: "없음", rottenTomatoes: 82, letterboxd: 4.2 },
    description: "두 형사가 연쇄 사건을 추적하는 범죄 스릴러."
  },
  {
    id: 59,
    title: "양들의 침묵",
    englishTitle: "The Silence of the Lambs",
    year: 1991,
    genre: ["범죄", "스릴러", "드라마"],
    aliases: ["양들의 침묵", "The Silence of the Lambs"],
    director: "조너선 드미",
    actors: ["조디 포스터", "앤서니 홉킨스"],
    poster: "",
    ratings: { imdb: 8.6, cine21: "없음", rottenTomatoes: 95, letterboxd: 4.1 },
    description: "수사관이 범죄자의 심리를 이용해 사건을 해결하려는 스릴러."
  },
  {
    id: 60,
    title: "라이언 일병 구하기",
    englishTitle: "Saving Private Ryan",
    year: 1998,
    genre: ["전쟁", "드라마"],
    aliases: ["라이언 일병 구하기", "Saving Private Ryan"],
    director: "스티븐 스필버그",
    actors: ["톰 행크스", "맷 데이먼"],
    poster: "",
    ratings: { imdb: 8.6, cine21: "없음", rottenTomatoes: 94, letterboxd: 4.1 },
    description: "전쟁 중 한 병사를 찾기 위해 떠나는 부대의 이야기."
  },
  {
    id: 61,
    title: "좋은 친구들",
    englishTitle: "GoodFellas",
    year: 1990,
    genre: ["범죄", "드라마"],
    aliases: ["좋은 친구들", "GoodFellas", "굿펠라스"],
    director: "마틴 스코세이지",
    actors: ["로버트 드 니로", "레이 리오타", "조 페시"],
    poster: "",
    ratings: { imdb: 8.7, cine21: "없음", rottenTomatoes: 96, letterboxd: 4.4 },
    description: "마피아 조직에 몸담은 남자의 삶을 그린 범죄 영화."
  },
  {
    id: 62,
    title: "레옹",
    englishTitle: "Léon: The Professional",
    year: 1994,
    genre: ["액션", "범죄", "드라마"],
    aliases: ["레옹", "Léon", "The Professional"],
    director: "뤽 베송",
    actors: ["장 르노", "나탈리 포트만"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 74, letterboxd: 4.1 },
    description: "고독한 인물과 한 소녀의 관계를 중심으로 펼쳐지는 액션 드라마."
  },
  {
    id: 63,
    title: "시네마 천국",
    englishTitle: "Cinema Paradiso",
    year: 1988,
    genre: ["드라마", "로맨스"],
    aliases: ["시네마 천국", "Cinema Paradiso"],
    director: "주세페 토르나토레",
    actors: ["필립 누아레", "자크 페렝"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 90, letterboxd: 4.2 },
    description: "영화관을 통해 성장과 영화에 대한 사랑을 그린 작품."
  },
  {
    id: 64,
    title: "카사블랑카",
    englishTitle: "Casablanca",
    year: 1942,
    genre: ["드라마", "로맨스"],
    aliases: ["카사블랑카", "Casablanca"],
    director: "마이클 커티즈",
    actors: ["험프리 보가트", "잉그리드 버그만"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 99, letterboxd: 4.2 },
    description: "전쟁 중 카사블랑카에서 다시 만난 두 사람의 이야기."
  },
  {
    id: 65,
    title: "인생은 아름다워",
    englishTitle: "Life Is Beautiful",
    year: 1997,
    genre: ["드라마", "코미디", "전쟁"],
    aliases: ["인생은 아름다워", "Life Is Beautiful"],
    director: "로베르토 베니니",
    actors: ["로베르토 베니니", "니콜레타 브라스키"],
    poster: "",
    ratings: { imdb: 8.6, cine21: 8.40, rottenTomatoes: 81, letterboxd: 4.0 },
    description: "어려운 시대 속에서도 가족을 지키려는 아버지의 이야기."
  },
  {
    id: 66,
    title: "이터널 선샤인",
    englishTitle: "Eternal Sunshine of the Spotless Mind",
    year: 2004,
    genre: ["SF", "드라마", "로맨스"],
    aliases: ["이터널 선샤인", "Eternal Sunshine"],
    director: "미셸 공드리",
    actors: ["짐 캐리", "케이트 윈슬렛"],
    poster: "",
    ratings: { imdb: 8.3, cine21: 8.25, rottenTomatoes: 92, letterboxd: 4.2 },
    description: "기억을 지우는 기술을 소재로 사랑과 기억을 탐구하는 영화."
  },
  {
    id: 67,
    title: "블레이드 러너",
    englishTitle: "Blade Runner",
    year: 1982,
    genre: ["SF", "스릴러"],
    aliases: ["블레이드 러너", "Blade Runner"],
    director: "리들리 스콧",
    actors: ["해리슨 포드", "룻거 하우어"],
    poster: "",
    ratings: { imdb: 8.1, cine21: 10.00, rottenTomatoes: 89, letterboxd: 4.2 },
    description: "미래 도시에서 복제 인간을 추적하는 형사의 이야기."
  },
  {
    id: 69,
    title: "모노노케 히메",
    englishTitle: "Princess Mononoke",
    year: 1997,
    genre: ["애니메이션", "판타지", "어드벤처"],
    aliases: ["모노노케 히메", "원령공주", "Princess Mononoke"],
    director: "미야자키 하야오",
    actors: ["마츠다 요지", "이시다 유리코"],
    poster: "",
    ratings: { imdb: 8.3, cine21: "없음", rottenTomatoes: 93, letterboxd: 4.3 },
    description: "인간과 자연의 갈등을 그린 미야자키 하야오의 애니메이션."
  },
  {
    id: 70,
    title: "센과 치히로의 행방불명",
    englishTitle: "Spirited Away",
    year: 2001,
    genre: ["애니메이션", "판타지", "어드벤처"],
    aliases: ["센과 치히로의 행방불명", "Spirited Away"],
    director: "미야자키 하야오",
    actors: ["히이라기 루미", "이리노 미유"],
    poster: "",
    ratings: { imdb: 8.6, cine21: "없음", rottenTomatoes: 96, letterboxd: 4.5 },
    description: "신비한 세계에 들어간 소녀 치히로의 성장 이야기."
  },
  {
    id: 71,
    title: "토이 스토리 3",
    englishTitle: "Toy Story 3",
    year: 2010,
    genre: ["애니메이션", "코미디", "어드벤처"],
    aliases: ["토이 스토리 3", "Toy Story 3"],
    director: "리 언크리치",
    actors: ["톰 행크스", "팀 앨런"],
    poster: "",
    ratings: { imdb: 8.3, cine21: "없음", rottenTomatoes: 98, letterboxd: 4.1 },
    description: "앤디의 성장과 장난감들의 새로운 여정을 그린 애니메이션."
  },
  {
    id: 72,
    title: "너의 이름은.",
    englishTitle: "Your Name.",
    year: 2016,
    genre: ["애니메이션", "판타지", "로맨스"],
    aliases: ["너의 이름은", "Your Name", "Kimi no Na wa"],
    director: "신카이 마코토",
    actors: ["카미키 류노스케", "카미시라이시 모네"],
    poster: "",
    ratings: { imdb: 8.4, cine21: "없음", rottenTomatoes: 98, letterboxd: 4.1 },
    description: "서로 다른 장소에 사는 두 사람이 신비로운 현상으로 연결되는 이야기."
  },
  {
    id: 73,
    title: "하울의 움직이는 성",
    englishTitle: "Howl's Moving Castle",
    year: 2004,
    genre: ["애니메이션", "판타지", "어드벤처"],
    aliases: ["하울의 움직이는 성", "Howl's Moving Castle"],
    director: "미야자키 하야오",
    actors: ["기무라 타쿠야", "바이쇼 치에코"],
    poster: "",
    ratings: { imdb: 8.2, cine21: "없음", rottenTomatoes: 87, letterboxd: 4.1 },
    description: "마법과 움직이는 성을 배경으로 한 판타지 애니메이션."
  },
  {
    id: 74,
    title: "라따뚜이",
    englishTitle: "Ratatouille",
    year: 2007,
    genre: ["애니메이션", "코미디"],
    aliases: ["라따뚜이", "Ratatouille"],
    director: "브래드 버드",
    actors: ["패튼 오스왈트", "이안 홈"],
    poster: "",
    ratings: { imdb: 8.1, cine21: "없음", rottenTomatoes: 96, letterboxd: 4.0 },
    description: "요리를 꿈꾸는 생쥐와 견습 요리사의 이야기를 그린 애니메이션."
  },
  {
    id: 75,
    title: "월-E",
    englishTitle: "WALL-E",
    year: 2008,
    genre: ["애니메이션", "SF", "어드벤처"],
    aliases: ["월-E", "WALL-E", "월E"],
    director: "앤드루 스탠턴",
    actors: ["벤 버트", "엘리사 나이트"],
    poster: "",
    ratings: { imdb: 8.4, cine21: "없음", rottenTomatoes: 95, letterboxd: 4.2 },
    description: "폐허가 된 지구에 홀로 남은 로봇의 이야기를 그린 작품."
  },
  {
    id: 76,
    title: "글래디에이터",
    englishTitle: "Gladiator",
    year: 2000,
    genre: ["액션", "드라마", "역사"],
    aliases: ["글래디에이터", "Gladiator"],
    director: "리들리 스콧",
    actors: ["러셀 크로우", "호아킨 피닉스"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 80, letterboxd: 4.1 },
    description: "로마 제국을 배경으로 복수를 꿈꾸는 장군의 이야기."
  },
  {
    id: 77,
    title: "터미네이터 2: 심판의 날",
    englishTitle: "Terminator 2: Judgment Day",
    year: 1991,
    genre: ["액션", "SF"],
    aliases: ["터미네이터 2", "Terminator 2"],
    director: "제임스 카메론",
    actors: ["아널드 슈워제네거", "린다 해밀턴"],
    poster: "",
    ratings: { imdb: 8.6, cine21: "없음", rottenTomatoes: 91, letterboxd: 4.1 },
    description: "미래의 운명을 둘러싼 SF 액션 영화."
  },
  {
    id: 78,
    title: "백 투 더 퓨처",
    englishTitle: "Back to the Future",
    year: 1985,
    genre: ["SF", "어드벤처", "코미디"],
    aliases: ["백 투 더 퓨처", "Back to the Future"],
    director: "로버트 저메키스",
    actors: ["마이클 J. 폭스", "크리스토퍼 로이드"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 93, letterboxd: 4.1 },
    description: "타임머신을 타고 과거로 가게 된 소년의 시간 여행 이야기."
  },
  {
    id: 79,
    title: "스타워즈: 제국의 역습",
    englishTitle: "Star Wars: Episode V - The Empire Strikes Back",
    year: 1980,
    genre: ["SF", "액션", "어드벤처"],
    aliases: ["제국의 역습", "The Empire Strikes Back", "Star Wars V"],
    director: "어빈 커슈너",
    actors: ["마크 해밀", "해리슨 포드", "캐리 피셔"],
    poster: "",
    ratings: { imdb: 8.7, cine21: "없음", rottenTomatoes: 95, letterboxd: 4.4 },
    description: "반란군과 제국의 갈등을 이어가는 스타워즈 시리즈."
  },
  {
    id: 80,
    title: "아마데우스",
    englishTitle: "Amadeus",
    year: 1984,
    genre: ["드라마", "음악", "역사"],
    aliases: ["아마데우스", "Amadeus"],
    director: "밀로스 포먼",
    actors: ["F. 머레이 에이브러햄", "톰 헐스"],
    poster: "",
    ratings: { imdb: 8.4, cine21: "없음", rottenTomatoes: 89, letterboxd: 4.1 },
    description: "모차르트와 살리에리의 관계를 중심으로 한 음악 드라마."
  },
  {
    id: 81,
    title: "시티 오브 갓",
    englishTitle: "City of God",
    year: 2002,
    genre: ["범죄", "드라마"],
    aliases: ["시티 오브 갓", "City of God"],
    director: "페르난도 메이렐레스",
    actors: ["알렉상드르 로드리게스"],
    poster: "",
    ratings: { imdb: 8.6, cine21: "없음", rottenTomatoes: 91, letterboxd: 4.5 },
    description: "브라질 빈민가에서 성장하는 소년들의 삶을 그린 범죄 드라마."
  },
  {
    id: 82,
    title: "피아니스트",
    englishTitle: "The Pianist",
    year: 2002,
    genre: ["드라마", "전쟁"],
    aliases: ["피아니스트", "The Pianist"],
    director: "로만 폴란스키",
    actors: ["애드리언 브로디"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 95, letterboxd: 4.2 },
    description: "전쟁 속에서 살아남으려는 피아니스트의 이야기."
  },
  {
    id: 83,
    title: "유주얼 서스펙트",
    englishTitle: "The Usual Suspects",
    year: 1995,
    genre: ["범죄", "미스터리", "스릴러"],
    aliases: ["유주얼 서스펙트", "The Usual Suspects"],
    director: "브라이언 싱어",
    actors: ["케빈 스페이시", "가브리엘 번"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 87, letterboxd: 4.0 },
    description: "한 사건을 둘러싼 인물들의 진술과 미스터리를 다룬 범죄 영화."
  },
  {
    id: 84,
    title: "장고: 분노의 추적자",
    englishTitle: "Django Unchained",
    year: 2012,
    genre: ["서부", "드라마", "액션"],
    aliases: ["장고", "장고: 분노의 추적자", "Django Unchained"],
    director: "쿠엔틴 타란티노",
    actors: ["제이미 폭스", "크리스토프 발츠"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 87, letterboxd: 4.0 },
    description: "한 남자가 자유를 되찾기 위해 여정을 떠나는 서부극."
  },
  {
    id: 85,
    title: "노인을 위한 나라는 없다",
    englishTitle: "No Country for Old Men",
    year: 2007,
    genre: ["범죄", "드라마", "스릴러"],
    aliases: ["노인을 위한 나라는 없다", "No Country for Old Men"],
    director: "코엔 형제",
    actors: ["토미 리 존스", "하비에르 바르뎀"],
    poster: "",
    ratings: { imdb: 8.2, cine21: "없음", rottenTomatoes: 93, letterboxd: 4.1 },
    description: "우연히 거액의 돈을 발견한 남자와 그를 쫓는 인물들의 이야기."
  },
  {
    id: 86,
    title: "그랜드 부다페스트 호텔",
    englishTitle: "The Grand Budapest Hotel",
    year: 2014,
    genre: ["코미디", "드라마", "어드벤처"],
    aliases: ["그랜드 부다페스트 호텔", "The Grand Budapest Hotel"],
    director: "웨스 앤더슨",
    actors: ["랄프 파인즈", "토니 레볼로리"],
    poster: "",
    ratings: { imdb: 8.1, cine21: "없음", rottenTomatoes: 92, letterboxd: 4.1 },
    description: "유럽의 한 호텔에서 벌어지는 우아하고 유쾌한 이야기."
  },
  {
    id: 87,
    title: "위플래쉬",
    englishTitle: "Whiplash",
    year: 2014,
    genre: ["드라마", "음악"],
    aliases: ["위플래쉬", "Whiplash"],
    director: "데이미언 셔젤",
    actors: ["마일스 텔러", "J.K. 시몬스"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 94, letterboxd: 4.1 },
    description: "최고의 연주자를 꿈꾸는 학생과 혹독한 지휘자의 이야기를 그린 음악 드라마."
  },
  {
    id: 88,
    title: "소셜 네트워크",
    englishTitle: "The Social Network",
    year: 2010,
    genre: ["드라마"],
    aliases: ["소셜 네트워크", "The Social Network"],
    director: "데이비드 핀처",
    actors: ["제시 아이젠버그", "앤드루 가필드"],
    poster: "",
    ratings: { imdb: 7.8, cine21: "없음", rottenTomatoes: 96, letterboxd: 3.9 },
    description: "한 인터넷 서비스의 탄생과 그 과정에서 벌어진 갈등을 다룬 영화."
  },
  {
    id: 89,
    title: "문라이트",
    englishTitle: "Moonlight",
    year: 2016,
    genre: ["드라마"],
    aliases: ["문라이트", "Moonlight"],
    director: "배리 젠킨스",
    actors: ["마허샬라 알리", "나오미 해리스"],
    poster: "",
    ratings: { imdb: 7.4, cine21: "없음", rottenTomatoes: 98, letterboxd: 3.9 },
    description: "한 남자의 성장과 정체성을 세 시기로 나누어 그린 드라마."
  },
  {
    id: 90,
    title: "타오르는 여인의 초상",
    englishTitle: "Portrait of a Lady on Fire",
    year: 2019,
    genre: ["드라마", "로맨스"],
    aliases: ["타오르는 여인의 초상", "Portrait of a Lady on Fire"],
    director: "셀린 시아마",
    actors: ["아델 에넬", "노에미 메를랑"],
    poster: "",
    ratings: { imdb: 8.0, cine21: "없음", rottenTomatoes: 97, letterboxd: 4.2 },
    description: "한 화가와 모델 사이의 관계를 그린 프랑스 영화."
  },
  {
    id: 91,
    title: "화양연화",
    englishTitle: "In the Mood for Love",
    year: 2000,
    genre: ["드라마", "로맨스"],
    aliases: ["화양연화", "In the Mood for Love"],
    director: "왕가위",
    actors: ["양조위", "장만옥"],
    poster: "",
    ratings: { imdb: 8.1, cine21: "없음", rottenTomatoes: 92, letterboxd: 4.4 },
    description: "좁은 공간에서 우연히 가까워진 두 사람의 감정을 그린 영화."
  },
  {
    id: 92,
    title: "중경삼림",
    englishTitle: "Chungking Express",
    year: 1994,
    genre: ["드라마", "로맨스", "코미디"],
    aliases: ["중경삼림", "Chungking Express"],
    director: "왕가위",
    actors: ["임청하", "양조위", "왕페이"],
    poster: "",
    ratings: { imdb: 8.0, cine21: "없음", rottenTomatoes: 95, letterboxd: 4.2 },
    description: "홍콩을 배경으로 두 경찰관의 사랑과 일상을 그린 작품."
  },
  {
    id: 93,
    title: "아비정전",
    englishTitle: "Days of Being Wild",
    year: 1990,
    genre: ["드라마", "로맨스"],
    aliases: ["아비정전", "Days of Being Wild"],
    director: "왕가위",
    actors: ["장국영", "장만옥", "유덕화"],
    poster: "",
    ratings: { imdb: 7.5, cine21: "없음", rottenTomatoes: 89, letterboxd: 4.1 },
    description: "자유로운 삶을 추구하는 남자와 주변 인물들의 관계를 그린 영화."
  },
  {
    id: 94,
    title: "라쇼몽",
    englishTitle: "Rashomon",
    year: 1950,
    genre: ["미스터리", "드라마"],
    aliases: ["라쇼몽", "Rashomon"],
    director: "구로사와 아키라",
    actors: ["미후네 도시로", "교 마치코"],
    poster: "",
    ratings: { imdb: 8.2, cine21: "없음", rottenTomatoes: 98, letterboxd: 4.3 },
    description: "하나의 사건을 서로 다른 시선으로 바라보는 고전 영화."
  },
  {
    id: 95,
    title: "자전거 도둑",
    englishTitle: "Bicycle Thieves",
    year: 1948,
    genre: ["드라마"],
    aliases: ["자전거 도둑", "Bicycle Thieves", "Bicycle Thief"],
    director: "비토리오 데 시카",
    actors: ["람베르토 마지오라니", "엔초 스타욜라"],
    poster: "",
    ratings: { imdb: 8.3, cine21: "없음", rottenTomatoes: 99, letterboxd: 4.3 },
    description: "전후 이탈리아에서 자전거를 잃어버린 아버지와 아들의 이야기."
  },
  {
    id: 96,
    title: "모던 타임즈",
    englishTitle: "Modern Times",
    year: 1936,
    genre: ["코미디", "드라마"],
    aliases: ["모던 타임즈", "Modern Times"],
    director: "찰리 채플린",
    actors: ["찰리 채플린", "폴레트 고다드"],
    poster: "",
    ratings: { imdb: 8.5, cine21: "없음", rottenTomatoes: 98, letterboxd: 4.3 },
    description: "산업화 시대 노동자의 삶을 풍자적으로 그린 작품."
  },
  {
    id: 97,
    title: "그랜드 호텔",
    englishTitle: "Grand Hotel",
    year: 1932,
    genre: ["드라마", "로맨스"],
    aliases: ["그랜드 호텔", "Grand Hotel"],
    director: "에드먼드 굴딩",
    actors: ["그레타 가르보", "존 배리모어"],
    poster: "",
    ratings: { imdb: 7.3, cine21: "없음", rottenTomatoes: 90, letterboxd: 3.7 },
    description: "한 호텔에 모인 여러 인물들의 이야기를 그린 고전 영화."
  },
  {
    id: 98,
    title: "아무도 모른다",
    englishTitle: "Nobody Knows",
    year: 2004,
    genre: ["드라마"],
    aliases: ["아무도 모른다", "Nobody Knows", "Dare mo Shiranai"],
    director: "고레에다 히로카즈",
    actors: ["야기라 유야", "키타우라 아유"],
    poster: "",
    ratings: { imdb: 8.0, cine21: 8.80, rottenTomatoes: 93, letterboxd: 4.1 },
    description: "도쿄의 한 아파트에서 살아가는 아이들의 이야기를 그린 작품."
  },
  {
    id: 99,
    title: "밀리언 달러 베이비",
    englishTitle: "Million Dollar Baby",
    year: 2004,
    genre: ["드라마", "스포츠"],
    aliases: ["밀리언 달러 베이비", "Million Dollar Baby"],
    director: "클린트 이스트우드",
    actors: ["힐러리 스웽크", "클린트 이스트우드", "모건 프리먼"],
    poster: "",
    ratings: { imdb: 8.1, cine21: 8.20, rottenTomatoes: 90, letterboxd: 4.0 },
    description: "복싱을 통해 자신의 꿈에 도전하는 한 여성의 이야기."
  },
  {
    id: 100,
    title: "아바타",
    englishTitle: "Avatar",
    year: 2009,
    genre: ["SF", "어드벤처", "액션"],
    aliases: ["아바타", "Avatar", "Avatar 2009"],
    director: "제임스 카메론",
    actors: ["샘 워싱턴", "조 샐다나", "시고니 위버"],
    poster: "",
    ratings: { imdb: 7.9, cine21: 9.29, rottenTomatoes: 82, letterboxd: 3.5 },
    description: "판도라 행성을 배경으로 인간과 나비족의 이야기를 그린 SF 영화."
  }
];
